# Generated by Django 3.1.7 on 2021-04-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_auto_20210416_0740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
        migrations.AlterModelOptions(
            name='defaultuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
