# Generated by Django 3.1.7 on 2021-05-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20210515_0311'),
        ('_auth', '0005_auto_20210515_0531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
