# Generated by Django 3.1.7 on 2021-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0007_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultuser',
            name='is_agent',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Agent'),
        ),
    ]
