# Generated by Django 3.1.7 on 2021-05-15 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0008_defaultuser_is_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='_auth.defaultuser'),
        ),
    ]
