# Generated by Django 3.1.7 on 2021-04-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0002_businesscenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProperty',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('area', models.FloatField(default=0, verbose_name='Area')),
                ('built_year', models.IntegerField(
                    default=2000, verbose_name='Year')),
                ('exploitation_year', models.IntegerField(
                    default=2000, verbose_name='Exploitation year')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='misc.address', verbose_name='Address')),
                ('business_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      to='misc.businesscenter', verbose_name='Business center')),
            ],
            options={
                'verbose_name': 'Commerical property',
                'verbose_name_plural': 'Commerical properties',
            },
        ),
    ]
