# Generated by Django 3.1.7 on 2021-04-14 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_residentialcomplex'),
        ('properties', '0002_houseproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('area', models.FloatField(default=0, verbose_name='Area')),
                ('built_year', models.IntegerField(default=2000, verbose_name='Year')),
                ('exploitation_year', models.IntegerField(default=2000, verbose_name='Exploitation year')),
                ('kitchen_area', models.FloatField(default=0, verbose_name='Kitchen area')),
                ('construction_type', models.CharField(default='', max_length=100, verbose_name='Construction type')),
                ('floor', models.PositiveIntegerField(default=0, verbose_name='Floor')),
                ('number_of_floors_in_house', models.PositiveIntegerField(default=0, verbose_name='Number of floors in the house')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.address', verbose_name='Address')),
                ('residential_complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.residentialcomplex')),
                ('rooms', models.ManyToManyField(to='misc.Room', verbose_name='Rooms')),
            ],
            options={
                'verbose_name': 'Flat property',
                'verbose_name_plural': 'Flat properties',
            },
        ),
    ]
