# Generated by Django 3.1.7 on 2021-04-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_flatproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='description',
            field=models.CharField(
                blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='number_of_rooms',
            field=models.IntegerField(
                default=2000, verbose_name='Exploitation year'),
        ),
        migrations.AddField(
            model_name='flatproperty',
            name='description',
            field=models.CharField(
                blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='flatproperty',
            name='number_of_bedrooms',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='flatproperty',
            name='number_of_rooms',
            field=models.IntegerField(
                default=2000, verbose_name='Exploitation year'),
        ),
        migrations.AddField(
            model_name='houseproperty',
            name='description',
            field=models.CharField(
                blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='houseproperty',
            name='number_of_bedrooms',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='houseproperty',
            name='number_of_rooms',
            field=models.IntegerField(
                default=2000, verbose_name='Exploitation year'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='built_year',
            field=models.PositiveIntegerField(
                default=2000, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='exploitation_year',
            field=models.PositiveIntegerField(
                default=2000, verbose_name='Exploitation year'),
        ),
        migrations.AlterField(
            model_name='flatproperty',
            name='built_year',
            field=models.PositiveIntegerField(
                default=2000, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='flatproperty',
            name='exploitation_year',
            field=models.PositiveIntegerField(
                default=2000, verbose_name='Exploitation year'),
        ),
        migrations.AlterField(
            model_name='houseproperty',
            name='built_year',
            field=models.PositiveIntegerField(
                default=2000, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='houseproperty',
            name='exploitation_year',
            field=models.PositiveIntegerField(
                default=2000, verbose_name='Exploitation year'),
        ),
    ]
