# Generated by Django 3.1.7 on 2021-04-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20210414_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialproperty',
            name='number_of_rooms',
            field=models.IntegerField(default=0, verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='flatproperty',
            name='number_of_rooms',
            field=models.IntegerField(default=0, verbose_name='Number of rooms'),
        ),
        migrations.AlterField(
            model_name='houseproperty',
            name='number_of_rooms',
            field=models.IntegerField(default=0, verbose_name='Number of rooms'),
        ),
    ]
