# Generated by Django 3.1.7 on 2021-04-24 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0004_delete_room'),
        ('properties', '0005_auto_20210414_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatproperty',
            name='residential_complex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.residentialcomplex'),
        ),
    ]
