# Generated by Django 3.1.7 on 2021-04-24 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0004_auto_20210416_0746'),
        ('properties', '0007_auto_20210424_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='_auth.defaultuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flatproperty',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='_auth.defaultuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='houseproperty',
            name='user',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='_auth.defaultuser'),
            preserve_default=False,
        ),
    ]
