# Generated by Django 3.1.7 on 2021-05-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_auto_20210424_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproperty',
            name='deal_type',
            field=models.SmallIntegerField(choices=[(0, 'Sell'), (1, 'Rent')], default=0),
        ),
        migrations.AddField(
            model_name='flatproperty',
            name='deal_type',
            field=models.SmallIntegerField(choices=[(0, 'Sell'), (1, 'Rent')], default=0),
        ),
        migrations.AddField(
            model_name='houseproperty',
            name='deal_type',
            field=models.SmallIntegerField(choices=[(0, 'Sell'), (1, 'Rent')], default=0),
        ),
    ]
