# Generated by Django 3.1.7 on 2021-04-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_businesscenter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Name')),
                ('number_of_floors', models.PositiveIntegerField(default=1, verbose_name='Number of floors')),
            ],
            options={
                'verbose_name': 'Residential complex',
                'verbose_name_plural': 'Residential complexes',
            },
        ),
    ]
