# Generated by Django 3.1.7 on 2021-04-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_residentialcomplex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
